// <auto-generated />
using System;
using Bunker.Domain.DBI;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Bunker.Api.Migrations
{
    [DbContext(typeof(BunkerDbContext))]
    partial class BunkerDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.10")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Bunker.Domain.Models.BunkerOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("AluminumContentPPM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("AnchorageArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("ApprovedDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("AshContentPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BargeCapacityMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BargeIMO")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BargeName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BerthNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("BioFuelBlend")
                        .HasColumnType("bit");

                    b.Property<decimal?>("BioFuelPercentage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CarbonFootprintMTCO2")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CarbonResiduePercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CertificateDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("CertificateIssuedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CertificateNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("CertificateValidUntil")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Currency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("DeliveryConfirmation")
                        .HasColumnType("bit");

                    b.Property<decimal?>("DeliveryDurationHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("DeliveryEndTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("DeliveryLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DeliveryMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DeliveryStartTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("DensityAt15C")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DiscountAmountUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DisputeDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("DisputeResolution")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("DisputeResolutionDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("DisputeStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("EnvironmentalCompliance")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ExchangeRate")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FinalAmountUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FlashPointCelsius")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("FuelType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("IMO2020Compliant")
                        .HasColumnType("bit");

                    b.Property<decimal?>("InvoiceAmountUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("InvoiceDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("InvoiceNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("LocalCurrency")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("LocalPrice")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("LowSulfurFuel")
                        .HasColumnType("bit");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("OrderNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("PaymentDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("PaymentDueDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("PaymentMethod")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PaymentTerms")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PipelineDelivery")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PipelineLengthMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("PortCallId")
                        .HasColumnType("int");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.Property<decimal?>("PourPointCelsius")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("QualityAcceptance")
                        .HasColumnType("bit");

                    b.Property<string>("QualityIssues")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("QualitySpecifications")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("QuantityMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RefundAmountUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RefundDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RequestedDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("SampleDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("SampleLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleReceivedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleSealedBy")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SampleStorageLocation")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("SampleTaken")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ScheduledDeliveryDate")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("SedimentContentPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("SiliconContentPPM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<decimal?>("SulfurContentPercent")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("SupplierAddress")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("SupplierContactPerson")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SupplierEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SupplierLicenseNumber")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SupplierName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("SupplierPhone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("SustainabilityCertificate")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TaxAmountUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TerminalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalPriceUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TruckCount")
                        .HasColumnType("int");

                    b.Property<string>("TruckLicensePlates")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("UnitPriceUSDPerMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("VanadiumContentPPM")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("VesselId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ViscosityAt50C")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VoyageId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WaterContentPercent")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PortCallId");

                    b.HasIndex("PortId");

                    b.HasIndex("VesselId");

                    b.HasIndex("VoyageId");

                    b.ToTable("BunkerOrders");
                });

            modelBuilder.Entity("Bunker.Domain.Models.Port", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("AlternativeName")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<decimal?>("AnnualCargoThroughputTEU")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("AnnualVesselCalls")
                        .HasColumnType("int");

                    b.Property<decimal?>("AverageTurnaroundTimeHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("AverageWaitingTimeHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("City")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("ContactEmail")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ContactPhone")
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("Country")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<bool>("HasBulkFacilities")
                        .HasColumnType("bit");

                    b.Property<bool>("HasBunkeringFacilities")
                        .HasColumnType("bit");

                    b.Property<bool>("HasContainerFacilities")
                        .HasColumnType("bit");

                    b.Property<bool>("HasLiquidFacilities")
                        .HasColumnType("bit");

                    b.Property<bool>("HasPassengerFacilities")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRepairFacilities")
                        .HasColumnType("bit");

                    b.Property<bool>("HasRoRoFacilities")
                        .HasColumnType("bit");

                    b.Property<bool>("Is24Hours")
                        .HasColumnType("bit");

                    b.Property<bool>("IsIceFree")
                        .HasColumnType("bit");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Latitude");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(18,2)")
                        .HasColumnName("Longitude");

                    b.Property<decimal?>("MaxDWT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaxDraft")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaxVesselBeam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("MaxVesselLength")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("NumberOfBerths")
                        .HasColumnType("int");

                    b.Property<int?>("NumberOfTerminals")
                        .HasColumnType("int");

                    b.Property<string>("PortAuthority")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("PortType")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("Size")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("State")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<string>("TimeZone")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("UNLOCODE")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("nvarchar(5)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Website")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("Id");

                    b.ToTable("Ports");
                });

            modelBuilder.Entity("Bunker.Domain.Models.PortCall", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualDeparture")
                        .HasColumnType("datetime2");

                    b.Property<string>("AnchorageArea")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("ArrivalDelayHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BerthCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BerthDraftMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BerthLengthMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BerthNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BerthType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BerthWidthMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BunkerCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("BunkerQuantityMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("BunkerSupplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("BunkerType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("BunkeringDurationHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("BunkeringEndTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("BunkeringRequired")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("BunkeringStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CallType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CargoHandlingDurationHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CargoHandlingEndTime")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("CargoHandlingRateMTPerHour")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CargoHandlingStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("CargoOperations")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("CargoVolumeM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CargoWeightMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ContainerCount")
                        .HasColumnType("int");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("CrewChangeCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("CrewChangeRequired")
                        .HasColumnType("bit");

                    b.Property<int?>("CrewJoiningCount")
                        .HasColumnType("int");

                    b.Property<int?>("CrewLeavingCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("CustomsClearanceCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("CustomsClearanceDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("CustomsClearanceRequired")
                        .HasColumnType("bit");

                    b.Property<string>("CustomsClearanceStatus")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("DepartureDelayHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DischargingWeightMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FreshWaterCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FreshWaterQuantityMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("FreshWaterRequired")
                        .HasColumnType("bit");

                    b.Property<bool>("HasIncidents")
                        .HasColumnType("bit");

                    b.Property<decimal?>("IncidentCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("IncidentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncidentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncidentSeverity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectionAuthority")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("InspectionCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("InspectionDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("InspectionRequired")
                        .HasColumnType("bit");

                    b.Property<string>("InspectionResult")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("InspectionType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsAnchorage")
                        .HasColumnType("bit");

                    b.Property<decimal?>("LoadingWeightMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PilotAssigned")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("PilotBoardingTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("PilotName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PilotRequired")
                        .HasColumnType("bit");

                    b.Property<decimal?>("PilotageCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("PortCallNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("PortChargesUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("PortId")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProvisionsCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("ProvisionsRequired")
                        .HasColumnType("bit");

                    b.Property<string>("ProvisionsSupplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Purpose")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RepairCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("RepairDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("RepairDurationHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("RepairEndTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("RepairStartTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("RepairSupplier")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RepairType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("RepairsRequired")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("ScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledDeparture")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeaState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<int?>("TEUCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("TerminalCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("TerminalName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("TerminalOperator")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("TotalDurationHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalPortCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("TugAssistanceRequired")
                        .HasColumnType("bit");

                    b.Property<decimal?>("TugCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("TugCount")
                        .HasColumnType("int");

                    b.Property<string>("TugNames")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VesselId")
                        .HasColumnType("int");

                    b.Property<decimal?>("VisibilityNauticalMiles")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("VoyageId")
                        .HasColumnType("int");

                    b.Property<decimal?>("WaveHeightMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WeatherConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WindSpeedKnots")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("PortId");

                    b.HasIndex("VesselId");

                    b.HasIndex("VoyageId");

                    b.ToTable("PortCalls");
                });

            modelBuilder.Entity("Bunker.Domain.Models.Vessel", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<decimal?>("Beam")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CallSign")
                        .HasMaxLength(10)
                        .HasColumnType("nvarchar(10)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("DeadweightTonnage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("Draft")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EnginePowerKW")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Flag")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("GrossTonnage")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("IMO")
                        .IsRequired()
                        .HasMaxLength(7)
                        .HasColumnType("nvarchar(7)");

                    b.Property<decimal?>("LengthOverall")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("MMSI")
                        .HasMaxLength(9)
                        .HasColumnType("nvarchar(9)");

                    b.Property<int?>("MaxCrew")
                        .HasColumnType("int");

                    b.Property<decimal?>("MaxSpeedKnots")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Owner")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("VesselType")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("YearBuilt")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.ToTable("Vessels");
                });

            modelBuilder.Entity("Bunker.Domain.Models.Voyage", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<DateTime?>("ActualArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ActualDeparture")
                        .HasColumnType("datetime2");

                    b.Property<decimal?>("ActualDurationHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("ArrivalPortId")
                        .HasColumnType("int");

                    b.Property<decimal?>("AverageSpeedKnots")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int>("BunkerOrderCount")
                        .HasColumnType("int");

                    b.Property<string>("CaptainName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("CargoOwner")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("CargoType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<decimal?>("CargoVolumeM3")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("CargoWeightMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<int?>("CharterDurationDays")
                        .HasColumnType("int");

                    b.Property<decimal?>("CharterRateUSDPerDay")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("CharterType")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<string>("Charterer")
                        .HasMaxLength(100)
                        .HasColumnType("nvarchar(100)");

                    b.Property<string>("ChiefEngineerName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("CreatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("CrewCount")
                        .HasColumnType("int");

                    b.Property<bool>("CrossesDateLine")
                        .HasColumnType("bit");

                    b.Property<bool>("CrossesEquator")
                        .HasColumnType("bit");

                    b.Property<decimal?>("DelayCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("DelayDurationHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("DelayReason")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("DeparturePortId")
                        .HasColumnType("int");

                    b.Property<decimal?>("DistanceNauticalMiles")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("EstimatedDurationHours")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FuelConsumptionMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("FuelCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<bool>("HasDelays")
                        .HasColumnType("bit");

                    b.Property<bool>("HasIncidents")
                        .HasColumnType("bit");

                    b.Property<DateTime?>("IncidentDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("IncidentDescription")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("IncidentSeverity")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("IsInternational")
                        .HasColumnType("bit");

                    b.Property<decimal?>("MaxSpeedKnots")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("Notes")
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("PassengerCount")
                        .HasColumnType("int");

                    b.Property<int>("PortCallCount")
                        .HasColumnType("int");

                    b.Property<decimal?>("ProfitLossUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("RevenueUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("ScheduledArrival")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("ScheduledDeparture")
                        .HasColumnType("datetime2");

                    b.Property<string>("SeaState")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int?>("TEUCount")
                        .HasColumnType("int");

                    b.Property<int?>("TimeZoneChanges")
                        .HasColumnType("int");

                    b.Property<decimal?>("TotalBunkerCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalBunkerQuantityMT")
                        .HasColumnType("decimal(18,2)");

                    b.Property<decimal?>("TotalCostUSD")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime?>("UpdatedAt")
                        .HasColumnType("datetime2");

                    b.Property<string>("UpdatedBy")
                        .HasMaxLength(50)
                        .HasColumnType("nvarchar(50)");

                    b.Property<int>("VesselId")
                        .HasColumnType("int");

                    b.Property<decimal?>("VisibilityNauticalMiles")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("VoyageNumber")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("nvarchar(20)");

                    b.Property<decimal?>("WaveHeightMeters")
                        .HasColumnType("decimal(18,2)");

                    b.Property<string>("WeatherConditions")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("WindSpeedKnots")
                        .HasColumnType("decimal(18,2)");

                    b.HasKey("Id");

                    b.HasIndex("ArrivalPortId");

                    b.HasIndex("DeparturePortId");

                    b.HasIndex("VesselId");

                    b.ToTable("Voyages");
                });

            modelBuilder.Entity("Bunker.Domain.Models.BunkerOrder", b =>
                {
                    b.HasOne("Bunker.Domain.Models.PortCall", "PortCall")
                        .WithMany("BunkerOrders")
                        .HasForeignKey("PortCallId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bunker.Domain.Models.Port", "Port")
                        .WithMany("BunkerOrders")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bunker.Domain.Models.Vessel", "Vessel")
                        .WithMany("BunkerOrders")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bunker.Domain.Models.Voyage", "Voyage")
                        .WithMany("BunkerOrders")
                        .HasForeignKey("VoyageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Port");

                    b.Navigation("PortCall");

                    b.Navigation("Vessel");

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("Bunker.Domain.Models.PortCall", b =>
                {
                    b.HasOne("Bunker.Domain.Models.Port", "Port")
                        .WithMany("PortCalls")
                        .HasForeignKey("PortId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bunker.Domain.Models.Vessel", "Vessel")
                        .WithMany("PortCalls")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Bunker.Domain.Models.Voyage", "Voyage")
                        .WithMany("PortCalls")
                        .HasForeignKey("VoyageId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Port");

                    b.Navigation("Vessel");

                    b.Navigation("Voyage");
                });

            modelBuilder.Entity("Bunker.Domain.Models.Voyage", b =>
                {
                    b.HasOne("Bunker.Domain.Models.Port", "ArrivalPort")
                        .WithMany("ArrivalVoyages")
                        .HasForeignKey("ArrivalPortId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bunker.Domain.Models.Port", "DeparturePort")
                        .WithMany("DepartureVoyages")
                        .HasForeignKey("DeparturePortId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Bunker.Domain.Models.Vessel", "Vessel")
                        .WithMany("Voyages")
                        .HasForeignKey("VesselId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ArrivalPort");

                    b.Navigation("DeparturePort");

                    b.Navigation("Vessel");
                });

            modelBuilder.Entity("Bunker.Domain.Models.Port", b =>
                {
                    b.Navigation("ArrivalVoyages");

                    b.Navigation("BunkerOrders");

                    b.Navigation("DepartureVoyages");

                    b.Navigation("PortCalls");
                });

            modelBuilder.Entity("Bunker.Domain.Models.PortCall", b =>
                {
                    b.Navigation("BunkerOrders");
                });

            modelBuilder.Entity("Bunker.Domain.Models.Vessel", b =>
                {
                    b.Navigation("BunkerOrders");

                    b.Navigation("PortCalls");

                    b.Navigation("Voyages");
                });

            modelBuilder.Entity("Bunker.Domain.Models.Voyage", b =>
                {
                    b.Navigation("BunkerOrders");

                    b.Navigation("PortCalls");
                });
#pragma warning restore 612, 618
        }
    }
}
